# Use the official httpd image as a base
FROM httpd

# Copy your HTML file into the default Apache document root
COPY ./index.html /usr/local/apache2/htdocs/





# # Expose the default HTTP port
# EXPOSE 80
